sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email:
    on_failure: always
node_js:
  - '6'
branches:
  only:
    - "master"

before_install:
  - npm i -g npm@^3.10.0
install:
  - npm install
before_script:
  - npm prune
before_deploy:
  - npm run dist
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: dzv3
  endpoint: dzv3.s3-website-us-east-1.amazonaws.com
  upload-dir: sfe-crossover-test
  local-dir: dist
  region: us-east-1
  acl: public_read
  detect_encoding: true

